# Generated by Django 5.0.7 on 2025-02-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrconfiguration',
            name='field_type',
            field=models.CharField(default='django.forms.CharField', help_text="Dotted path to the Django form field class (e.g., 'django.forms.CharField').", max_length=255),
        ),
    ]
