# Generated by Django 5.0.7 on 2025-02-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_attrconfiguration_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttrValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, help_text='The value of the attribute.', null=True)),
                ('key', models.ForeignKey(help_text='The attribute configuration.', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='attributes.attrconfiguration')),
            ],
        ),
    ]
