# Generated by Django 5.0.7 on 2025-02-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_attrconfiguration_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrconfiguration',
            name='args',
            field=models.JSONField(blank=True, default=list, help_text='A JSON array of positional arguments to pass to the field constructor.'),
        ),
        migrations.AddField(
            model_name='attrconfiguration',
            name='kwargs',
            field=models.JSONField(blank=True, default=dict, help_text='A JSON object of keyword arguments to pass to the field constructor.'),
        ),
    ]
