# Generated by Django 5.0.7 on 2025-02-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0005_attrconfiguration_args_attrconfiguration_kwargs'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrvalue',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Determines the order of the values.'),
        ),
    ]
