# Generated by Django 5.0.7 on 2025-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0006_attrvalue_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrvalue',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='The last time this value was updated.'),
        ),
    ]
