# Generated by Django 5.0.7 on 2025-02-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0007_attrvalue_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrconfiguration',
            name='return_type',
            field=models.CharField(choices=[('list', 'List'), ('dict', 'Dictionary'), ('set', 'Set'), ('first', 'First'), ('last', 'Last')], default='first', help_text='How to return attribute values in cache.', max_length=10),
        ),
    ]
